"""`.dreadap` file: per-player metadata generated by AP world-gen.

The `.dreadap` file is the user-facing entry point. Generated per-player when
the multiworld is created (see `DreadWorld.generate_output` in the apworld's
`__init__.py`), shipped inside the per-player zip alongside the standard AP
artifacts. The user double-clicks it; Archipelago Launcher resolves the file
extension via `SuffixIdentifier('.dreadap')` in the Component registration and
hands the path to `launch_dread_client`, which parses the .dreadap and launches
DreadClient with `--name` (and optionally `--connect`) pre-filled, so the
user lands in the Connect bar ready to go. The setup wizard is invoked
separately via `/setup` inside DreadClient.

The format is intentionally tiny — just enough to identify *which slot* this
player is. Everything else (bridge IP, deploy target, paths) is per-machine
state managed by the setup wizard. AP server address is optional because the
generator's host may not know it (self-hosted vs archipelago.gg vs ...);
DreadClient will prompt via the Connect bar when it's empty.

**On-disk format**: a ZIP archive containing `metadata.json`. This matches the
convention every other `.ap*` patch file follows in Archipelago, so users who
rename `.dreadap` → `.zip` and extract get the underlying metadata as they'd
expect. The reader also accepts a bare-JSON `.dreadap` for back-compat with files
generated by earlier alpha builds (pre-zip-wrapping) — sniffed via the magic
bytes, no version flag needed.

Schema is versioned so future fields can land without breaking older clients.
"""

from __future__ import annotations

import io
import json
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

DREAD_AP_SCHEMA_VERSION = 1
GAME_NAME = "Metroid Dread"

# Filename used inside the ZIP wrapper. Constant rather than hard-coded at
# every call site so future archive contents (icons, scout results) can land
# alongside without breaking the reader.
DREAD_AP_METADATA_ENTRY = "metadata.json"


@dataclass
class DreadapFile:
    """In-memory form of a `.dreadap` file.

    `server_address` and `password` may be empty strings — DreadClient will
    fall back to the Connect-bar prompt in that case.
    """
    slot_name: str
    seed_name: str = ""
    server_address: str = ""
    password: str = ""
    game: str = GAME_NAME
    version: int = DREAD_AP_SCHEMA_VERSION

    def to_dict(self) -> dict[str, Any]:
        return {
            "game": self.game,
            "version": self.version,
            "slot_name": self.slot_name,
            "seed_name": self.seed_name,
            "server_address": self.server_address,
            "password": self.password,
        }

    def to_json(self) -> str:
        # `sort_keys=False` keeps the human-readable order — `game` and
        # `version` first so a human eyeballing the file knows what it is.
        return json.dumps(self.to_dict(), indent=2)

    def write(self, path: Path) -> None:
        """Write a ZIP-wrapped `.dreadap`. Single entry `metadata.json` holds
        the JSON payload, indented for human-readability after extraction."""
        with zipfile.ZipFile(path, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.writestr(DREAD_AP_METADATA_ENTRY, self.to_json())


def _read_dreadap_bytes(path: Path) -> str:
    """Pull the JSON payload out of a `.dreadap` file on disk.

    Accepts both the ZIP-wrapped format (current) and bare-JSON (back-compat
    with alpha builds that wrote raw JSON). Sniffs the magic bytes — no
    version field needed because the two formats can't collide (`PK` is not
    valid leading whitespace for JSON, and `{` is not a ZIP magic byte)."""
    raw = path.read_bytes()
    if raw[:2] == b"PK":
        with zipfile.ZipFile(io.BytesIO(raw)) as zf:
            try:
                data = zf.read(DREAD_AP_METADATA_ENTRY)
            except KeyError as e:
                raise ValueError(
                    f"dreadap zip is missing required entry {DREAD_AP_METADATA_ENTRY!r}"
                ) from e
        return data.decode("utf-8")
    return raw.decode("utf-8")


def parse_dreadap(text_or_path: str | Path) -> DreadapFile:
    """Read a `.dreadap` file (path or raw JSON text) and return a DreadapFile.

    Raises `ValueError` for malformed JSON, missing required fields, or an
    unknown game/version combination. Forward-compatible: unknown keys are
    silently ignored so a future-version client can add fields without
    breaking older ones (game/version mismatch is the explicit break point).
    """
    if isinstance(text_or_path, Path):
        text = _read_dreadap_bytes(text_or_path)
    else:
        # Heuristic: if it starts with `{` it's JSON; otherwise treat as path.
        # (Pure-JSON callers always pass via Path or wrap their JSON in
        # this string form intentionally; this branch lets tests pass raw
        # JSON without bouncing off the filesystem.)
        s = text_or_path.lstrip()
        if s.startswith("{"):
            text = text_or_path
        else:
            text = _read_dreadap_bytes(Path(text_or_path))

    try:
        d = json.loads(text)
    except json.JSONDecodeError as e:
        raise ValueError(f"invalid JSON: {e}") from e

    if not isinstance(d, dict):
        raise ValueError("expected JSON object")

    game = d.get("game")
    if game != GAME_NAME:
        raise ValueError(
            f"unexpected game={game!r}; this .dreadap is not for {GAME_NAME!r}"
        )

    version = d.get("version")
    if not isinstance(version, int) or version < 1:
        raise ValueError(f"missing or invalid version={version!r}")
    if version > DREAD_AP_SCHEMA_VERSION:
        raise ValueError(
            f"dreadap version {version} is newer than client supports "
            f"({DREAD_AP_SCHEMA_VERSION}); upgrade Dread Archipelago"
        )

    slot_name = d.get("slot_name") or ""
    if not isinstance(slot_name, str) or not slot_name:
        raise ValueError("slot_name is required and must be a non-empty string")

    return DreadapFile(
        slot_name=slot_name,
        seed_name=str(d.get("seed_name") or ""),
        server_address=str(d.get("server_address") or ""),
        password=str(d.get("password") or ""),
        game=game,
        version=version,
    )


def dreadap_to_launch_args(s: DreadapFile) -> list[str]:
    """Translate a DreadapFile into DreadClient CLI args (`--name`, `--connect`,
    `--password`).

    Empty fields are omitted — DreadClient already handles missing `--connect`
    by leaving the GUI Connect bar blank, and missing `--name` by leaving
    `ctx.auth` unset until the user types one.
    """
    out: list[str] = ["--name", s.slot_name]
    if s.server_address:
        out += ["--connect", s.server_address]
    if s.password:
        out += ["--password", s.password]
    return out
