"""`.dreadap` file: per-player metadata generated by AP world-gen.

The `.dreadap` is the user-facing entry point. `DreadWorld.generate_output`
writes one per player into the seed zip; the Archipelago Launcher resolves the
extension via `SuffixIdentifier('.dreadap')` (registered in the apworld's
`__init__.py`) and hands the path to `launch_dread_client`, which parses it and
launches the client with `--name` (and optionally `--connect`/`--password`)
pre-filled. The user lands in the Connect bar ready to go.

The format is intentionally tiny — just enough to identify *which slot* this
player is. The AP server address is optional because the generator's host may
not know it (self-hosted vs archipelago.gg vs ...); the client prompts via the
Connect bar when it's empty. Everything else (romfs / mod-install paths) is
per-machine state the client remembers across `/patch` runs, not seed data.

**On-disk format**: a ZIP archive containing `metadata.json` — the convention
every `.ap*` patch file follows, so renaming `.dreadap` → `.zip` and extracting
yields the metadata. The reader also accepts a bare-JSON `.dreadap` (sniffed via
magic bytes) for forward/backward tolerance.
"""
from __future__ import annotations

import io
import json
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

DREADAP_SCHEMA_VERSION = 1
GAME_NAME = "Metroid Dread"

# Filename inside the ZIP wrapper; a constant so future archive contents can
# land alongside without breaking the reader.
DREADAP_METADATA_ENTRY = "metadata.json"


@dataclass
class DreadapFile:
    """In-memory form of a `.dreadap` file.

    `server_address` and `password` may be empty — the client falls back to the
    Connect-bar prompt in that case."""
    slot_name: str
    seed_name: str = ""
    server_address: str = ""
    password: str = ""
    game: str = GAME_NAME
    version: int = DREADAP_SCHEMA_VERSION

    def to_dict(self) -> dict[str, Any]:
        return {
            "game": self.game,
            "version": self.version,
            "slot_name": self.slot_name,
            "seed_name": self.seed_name,
            "server_address": self.server_address,
            "password": self.password,
        }

    def to_json(self) -> str:
        # game/version first so a human eyeballing the file knows what it is.
        return json.dumps(self.to_dict(), indent=2)

    def write(self, path: Path) -> None:
        """Write a ZIP-wrapped `.dreadap` with a single `metadata.json` entry."""
        with zipfile.ZipFile(path, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.writestr(DREADAP_METADATA_ENTRY, self.to_json())


def _read_dreadap_text(path: Path) -> str:
    """Pull the JSON payload out of a `.dreadap` on disk.

    Accepts the ZIP-wrapped format and bare JSON, sniffed via magic bytes —
    `PK` (zip) can't be valid leading JSON, and `{` can't be a zip header, so
    the two never collide."""
    raw = path.read_bytes()
    if raw[:2] == b"PK":
        with zipfile.ZipFile(io.BytesIO(raw)) as zf:
            try:
                data = zf.read(DREADAP_METADATA_ENTRY)
            except KeyError as e:
                raise ValueError(
                    f"dreadap zip is missing required entry {DREADAP_METADATA_ENTRY!r}"
                ) from e
        return data.decode("utf-8")
    return raw.decode("utf-8")


def parse_dreadap(text_or_path: str | Path) -> DreadapFile:
    """Read a `.dreadap` (path or raw JSON text) into a DreadapFile.

    Raises `ValueError` for malformed JSON, a missing slot_name, or a
    game/version mismatch. Unknown keys are ignored so a future-version file
    can add fields without breaking older clients."""
    if isinstance(text_or_path, Path):
        text = _read_dreadap_text(text_or_path)
    else:
        s = text_or_path.lstrip()
        text = text_or_path if s.startswith("{") else _read_dreadap_text(Path(text_or_path))

    try:
        d = json.loads(text)
    except json.JSONDecodeError as e:
        raise ValueError(f"invalid JSON: {e}") from e
    if not isinstance(d, dict):
        raise ValueError("expected JSON object")

    game = d.get("game")
    if game != GAME_NAME:
        raise ValueError(f"unexpected game={game!r}; this .dreadap is not for {GAME_NAME!r}")

    version = d.get("version")
    if not isinstance(version, int) or version < 1:
        raise ValueError(f"missing or invalid version={version!r}")
    if version > DREADAP_SCHEMA_VERSION:
        raise ValueError(
            f"dreadap version {version} is newer than this client supports "
            f"({DREADAP_SCHEMA_VERSION}); upgrade the Dread apworld"
        )

    slot_name = d.get("slot_name") or ""
    if not isinstance(slot_name, str) or not slot_name:
        raise ValueError("slot_name is required and must be a non-empty string")

    return DreadapFile(
        slot_name=slot_name,
        seed_name=str(d.get("seed_name") or ""),
        server_address=str(d.get("server_address") or ""),
        password=str(d.get("password") or ""),
        game=game,
        version=version,
    )


def dreadap_to_launch_args(d: DreadapFile) -> list[str]:
    """Translate a DreadapFile into DreadClient CLI args.

    Empty fields are omitted — the client handles a missing `--connect` by
    leaving the Connect bar blank and a missing `--name` by leaving `auth`
    unset until the user types one."""
    out: list[str] = ["--name", d.slot_name]
    if d.server_address:
        out += ["--connect", d.server_address]
    if d.password:
        out += ["--password", d.password]
    return out
